# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  minitwitbackend:
    build: ./minitwit-backend
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
  minitwitfrontend:
    build: ./minitwit-frontend
    ports:
      - 3000:3000
