# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

networks:
    main:
        name: itu-minitwit-network

services:
  minitwitbackend:
    build: ./minitwit-backend
    container_name: minitwit-backend
    ports:
      - 3005:3005
      - 3006:3006
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:3006
      - ASPNETCORE_URLS=http://+:3005
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - type: bind
        source: ./databasefile
        target: /databasefile
    networks:
        - main
    depends_on:
        - grafana
        - prometheus

  minitwitfrontend:
    build: ./minitwit-frontend
    container_name: minitwit-frontend
    ports:
      - 3000:3000
    networks:
        - main
    depends_on:
        - minitwitbackend
        - prometheus
        - grafana

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
          - prometheus-storage:/prometheus
      ports:
          - "9090:9090"
      networks:
          - main

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      volumes:
        - ./grafana-storage:/var/lib/grafana
      ports:
          - "9099:3000"
      networks:
          - main
      depends_on:
          - prometheus

volumes:
    grafana-storage:
    prometheus-storage: